# **Mathématiques pour l'Intelligence Artificielle**  
### International Olympiad in Artificial Intelligence (IOAI) 2025
### Trainer : Audrey FANGNON  
----

## **Chapitre 1 : Algèbre Linéaire**  
##### C'est quoi ? L’algèbre linéaire est la branche des mathématiques qui s'intéresse aux espaces vectoriels et aux transformations linéaires.
##### Role: Il fournit les outils mathématiques pour représenter, manipuler et optimiser les données et les modèles en intelligence artificielle.
##### Vocabulaire: 
- **Espace vectoriel** : Un ensemble de vecteurs fermé sous addition et multiplication par un scalaire (ex: $(ℝ^n, +, \times)$).  
- **Base** : Un ensemble de vecteurs linéairement indépendants qui engendrent l'espace (ex: $((1,0),(0,1))$ est une base de $ℝ^2$) 
- **Dimension** : Nombre de vecteurs dans une base (ex: dim$(\mathbb{R}^3) = 3$)).

### **1.1. Vecteurs** 

----

### **1.1.1. Notion de base sur les vecteurs**  

----
  
### **A. Définition et représentation**  
Un **vecteur** est un objet mathématique caractérisé par :  
  - **Une direction**: celle du support du vecteur.
  - **Un sens**: le sens de parcours du vecteur.
  - **Une norme**: la longueur du vecteur.  
  
**Exemple :** Si A et B sont deux points distincts, quelles sont les caractéristiques de $\overrightarrow{AB}$ ?
  - **Direction:**  ---
  - **Sens:**  --
  - **Norme:** --


### **B. Opérations de base**  
Considerons deux vecteurs $ \vec{u}(u_1, u_2, ..., u_n)$ et $\vec{v}(v_1, v_2, ..., v_n)$ de $\mathbb{R}^n$
- **Addition** : $  \vec{u} + \vec{v} = \begin{pmatrix} u_1 + v_1 \\ u_2 + v_2 \\ . \\ . \\ . \\ u_n + v_n \end{pmatrix}  $
- **Multiplication par un scalaire** : $  \lambda \vec{v} = \begin{pmatrix} \lambda v_1 \\ \lambda v_2 \\ . \\ . \\ . \\ \lambda v_n \end{pmatrix} $ où $\lambda$ est un scalaire (élément de $\mathbb{R}$ ou de $\mathbb{C}$)

### **C. Vecteurs en IA**  
En machine learning, un vecteur peut représenter :  
- Un point dans un espace de caractéristiques (*features*).
- Des mots et phrases (word embeddings en NLP) 
- Les poids dans un réseau de neurones.

### **Exercices d'application (1.1.1)**  
1. Soient $ \vec{u} = \begin{pmatrix} 2 \\ 1 \end{pmatrix} $ et $ \vec{v} = \begin{pmatrix} 2 \\ 0 \end{pmatrix} $.
Calculez $  \vec{u} + \vec{v}  $ et  $  2\vec{v} - \vec{u}. $
2. Représentez graphiquement $ \vec{w} = \begin{pmatrix} 4 \\ 1 \end{pmatrix} $ dans le plan.


In [ ]:
import numpy as np

u = np.array([2, 1]) ; v = np.array([2, 0])
print(f" u + v : {u + v} \n 2v - u : {2*v-u}")

In [ ]:
import matplotlib.pyplot as plt
import numpy as np

# Définition des points A, B et C puis Calcul des vecteurs
A = np.array([0, 0]); B = np.array([2, 1]) ; C = np.array([4, 1])
AB = B - A; BC = C - B; AC = C - A
# Création de la figure
ax = plt.gca()
ax.set_aspect('equal')
ax.quiver(*A, *AB, angles='xy', scale_units='xy', scale=1, color='blue')
ax.quiver(*B, *BC, angles='xy', scale_units='xy', scale=1, color='green')
ax.quiver(*A, *AC, angles='xy', scale_units='xy', scale=1, color='red')
# Ajout des points
for point, name in zip([A, B, C], ['A', 'B', 'C']):
    ax.plot(*point, 'ko')
    ax.text(point[0] + 0.1, point[1] + 0.1, name, fontsize=12)
# Configuration de l'axe
plt.grid(True)
plt.title(f"Titre : Relation de Chasles {'  '*20}")
plt.show()

----
### **1.1.2. Produit scalaire et applications**  
----

#### **A. Définition**  

##### Définition 1: (Projective)
Le produit scalaire de deux vecteurs $\vec{u}$ et $\vec{v}$ est défini par: 
$$ \vec{u} \cdot \vec{v} = \|\vec{u}\| \times \|\vec{v}\| \times cos(\vec{u}, \vec{v}) $$


##### Définition 2: (Dans $\mathbb{R}^n$)
Le produit scalaire de deux vecteurs $ \vec{u}(u_1, u_2, ..., u_n)$ et $\vec{v}(v_1, v_2, ..., v_n)$ de $\mathbb{R}^n$ est :  
$$ \vec{u} \cdot \vec{v} = \sum_{i = 1}^{n} {u_i \times v_i} = u_1 v_1 + u_2 v_2 + \dots + u_n v_n $$  

#### **B. Propriétés**  
- **Symétrie** : $ \vec{u} \cdot \vec{v} = \vec{v} \cdot \vec{u} $  
- **Linéarité** : $ \vec{u} \cdot (\vec{v} + \vec{w}) = \vec{u} \cdot \vec{v} + \vec{u} \cdot \vec{w} $

#### **C. Interprétation**
![Interpretaion du produit scalaire](produit_scalaire_interpretation.png)
 - À gauche (produit scalaire positif) : les vecteurs pointes dans des directions presque similaires.
 - Au milieu (produit scalaire négatif) : les vecteurs pointes dans des directions presque opposées.
 - À droite (produit scalaire nul): les vecteurs pointes dans des directions différente.

#### **D. Applications en IA**  
- **Similarité cosinus** : Mesure la similarité entre deux vecteurs.  
  $\cos(\theta) = \frac{\vec{u} \cdot \vec{v}}{\|\vec{u}\| \|\vec{v}\|} $  
Si le cosinus est proche de 1, les vecteurs pointent dans la même direction (ils sont similaires).

- Utilisé en NLP (*Natural Language Processing*) pour comparer des documents, mots, phrases (word embeddings).  
  
### **Exercices d'application (1.1.2)**
On donne les vecteurs : $\vec{u} = \begin{pmatrix} 0 \\ 2 \end{pmatrix}$, $ \vec{v} = \begin{pmatrix} 2 \\ 1 \end{pmatrix}$, $\vec{w} = \begin{pmatrix} 2 \\ -7 \end{pmatrix}$ et $\vec{\Omega} = \begin{pmatrix} 1 \\ -2 \end{pmatrix}$.
1. Calculez $\vec{\Omega} \cdot \vec{u}$, $\vec{\Omega} \cdot \vec{v}$ et $\vec{\Omega} \cdot \vec{w}$.  
2. En utilisant la similarité cosinus trouve :  
   2.1. le vecteur le plus similaire à $\vec{\Omega}$.  
   2.2. le vecteur le moins similaire à $\vec{\Omega}$

In [ ]:
# Illustration
u = np.array([0, 2]) ; v = np.array([2, 1]) ; w = np.array([3, -2]) ; omega = np.array([1, -2]) ; O = np.array([0, 0]) 
# Création de la figure
ax = plt.gca()
ax.set_aspect('equal')
ax.quiver(*O, *u, angles='xy', scale_units='xy', scale=1, color='blue')
ax.quiver(*O, *v, angles='xy', scale_units='xy', scale=1, color='green')
ax.quiver(*O, *w, angles='xy', scale_units='xy', scale=1, color='red')
ax.quiver(*O, *omega, angles='xy', scale_units='xy', scale=1, color='yellow')
# Ajout des points et calcul de similarité
for point, name in zip([u, v, w, omega], ['u', 'v', 'w', 'omega']):
    ax.plot(*point)
    ax.text(point[0] + 0.1, point[1] + 0.1, name, fontsize=12)
# Configuration de l'axe
plt.grid(True)
plt.title(f"Graphique: application 1.1.3")
plt.show()

### TP : Utilisation des vecteurs en NLP et Similarité cosinus

In [ ]:
#!pip install google-genai

from google import genai
from google.genai import types
from sklearn.metrics.pairwise import cosine_similarity

GEMINI_API_KEY='AIzaSyBPp-b8SicH-_NzQcwtUX36z6G186zFAMA'
client = genai.Client(api_key=GEMINI_API_KEY)
def vectorize(input, model="gemini-embedding-exp-03-07"):
    result = client.models.embed_content(
            model=model,
            contents=input
    )
    return np.array(result.embeddings[0].values).reshape(1, -1)
print(cosine_similarity(vectorize("Il fait beau"), vectorize("")))

----
### **1.1.3. Normes (L1, L2)**  
----
Les normes L1 et L2 donnent des mesures différentes de la "taille" d'un vecteur, avec des interprétations géométriques distinctes.  

#### **A. Norme L1 (Norme Manhattan)**  
La norme L1 d'un vecteur **$v = (v₁, v₂, ..., vₙ)$** de $\mathbb{R}^n$ est la somme des valeurs absolues de ses composantes :  
$ ||v||_1 = |v_1| + |v_2| + \dots + |v_n| $ 

##### **Interprétation géométrique**  
- **En 2D/3D** : La norme L1 représente la distance parcourue en suivant un chemin en "escalier" (comme les déplacements dans une ville quadrillée, d'où le nom *Manhattan*).  
- **Exemple** :  
  - Pour **v = (3, 4)** (en 2D), la norme L1 est **7**.  

##### **Applications pratiques**  
- **En IA** :  
  - Utilisée en *régularisation Lasso* pour éliminer les variables non pertinentes (certains coefficients deviennent exactement **0**).  
  - Moins sensible aux *outliers* que L2 (car elle ne pénalise pas trop les grandes valeurs).  


#### **B. Norme L2 (Norme Euclidienne)**   
La norme L2 est la racine carrée de la somme des carrés des composantes :  
$ ||v||_2 = \sqrt{v_1^2 + v_2^2 + \dots + v_n^2} $

##### **Interprétation géométrique**  
- **En 2D/3D** : C'est la distance "à vol d'oiseau" entre l'origine et le point représenté par le vecteur.  
- **Exemple** :  
  - Pour **v = (3, 4)**, la norme L2 est **5** (car $ \sqrt{3^2 + 4^2} = 5 $).  
  - C'est la longueur du segment reliant **(0,0)** à **(3,4)**.   

##### **Applications pratiques**  
- **En IA** :  
  - Utilisée en *régularisation Ridge* pour réduire l'amplitude des coefficients sans les annuler.  
  - Très courante en *descente de gradient* (car elle est différentiable partout).  
  - Sensible aux *outliers* (car les grandes valeurs sont amplifiées par le carré).  


### **Exercices d'application (1.1.3)**

Soient $ \vec{a} = \begin{pmatrix} 1 \\ 0 \\ -1 \end{pmatrix} $ et $ \vec{b} = \begin{pmatrix} 2 \\ -1 \\ 3 \end{pmatrix} $.  
1. Calculez $ \vec{a} \cdot \vec{a} $, et $ \vec{b} \cdot \vec{b} $  
2. Calculer les normes $ \| . \|_1 $ et $ \| . \|_2 $ de ces vecteurs.
3. Quelle relation y a-t-il entre : **le produit scalaire** et  $ \| . \|_2 $.


## **1.2. Matrices et Applications Linéaires**

----
### **1.2.1. Matrice et Application Linéaire**  
----
  
#### **A. Définition d’une Matrice**  
Une **matrice** est un tableau rectangulaire de nombres réels (ou complexes) disposés en lignes et colonnes.  

**Exemple :** 


$
A = \begin{pmatrix}
1 & 2 & 3 \\
4 & 5 & 6 \\
7 & 8 & 9
\end{pmatrix}
$ $\quad$
$
B = \begin{pmatrix}
1 & 2 & 3 \\
2 & 9 & 6 \\
\end{pmatrix}
$ $\quad$
$
C = \begin{pmatrix}
4 \\
0 \\
7 \\
\end{pmatrix}
$ $\quad$
$
D = \begin{pmatrix}
3 & 2 & 3 \\
\end{pmatrix}
$ et 
$
I_3 = \begin{pmatrix}
1 & 0 & 0 \\
0 & 1 & 0 \\
0 & 0 & 1
\end{pmatrix}
$
- **Format de la matrice A :** $ ( 3 \times 3 ) $ (3 lignes, 3 colonnes).  
- **Format de la matrice B :** $ ( 2 \times 3 ) $ (2 lignes, 3 colonnes).



#### **B. Application Linéaire et Matrice**  
Une **application linéaire** $ f: \mathbb{R}^n \rightarrow \mathbb{R}^m $ peut être représentée par une matrice.  

**Exemple :**  
Soit $ f: \mathbb{R}^3 \rightarrow \mathbb{R}^3 $ définie par :
$ f(x, y, z) = (x + 2y + 3z, 4x + 5y + 6z, 7x + 8y + 9z) $  

Sa matrice associée est :
$
A = \begin{pmatrix}
1 & 2 & 3 \\
4 & 5 & 6 \\
7 & 8 & 9
\end{pmatrix}
$  

**Interprétation :**  
$
f(x, y, z) = A \begin{pmatrix} x \\ y \\ z \end{pmatrix}
$ 


### **Exercices d'application (1.2.1)**  
On donne : $ f: \mathbb{R}^3 \rightarrow \mathbb{R}^3 $ définie par :
$ f(x, y, z) = (y + 3z, 4x - 7z, x ) $ puis la matrice :
$
Z = \begin{pmatrix}
1 & 0 & -5 \\
0 & 5 & 2 \\
\end{pmatrix}
$ 

1. Donne la matrice $M$ associée à $f$. 
2. Donne l'application linéaire $h$ associée à $Z$ puis calcule l'image de $(0; 1; 0)$ par $h$.


In [28]:
# Représentation d'une matrice avec numpy
import numpy as np

A = np.array([
    [2, -1, 1, 0],
    [1, 3, -2, 1],
    [-1, 4, 5, 0]
])
print(f'format de la Matrice A : {A.shape}')
print(f'Nombre de coefficient dans A : {A.size}')

format de la Matrice A : (3, 4)
Nombre de coefficient dans A : 12


----
### **1.2.2. Opérations sur les Matrices** 
----
#### **A. Addition de Matrices**  
Si $A$ et $B$ sont deux matrices de même taille, alors $ C = A + B $ est définie par :
$
c_{ij} = a_{ij} + b_{ij}
$  

**Exemple :**  


$
A = \begin{pmatrix}
1 & 2 & 3 \\
4 & 5 & 6 \\
7 & 8 & 9
\end{pmatrix}, \qquad
B = \begin{pmatrix}
9 & 8 & 7 \\
6 & 5 & 4 \\
3 & 2 & 1
\end{pmatrix}
$    

$
A + B = \begin{pmatrix}
1+9 & 2+8 & 3+7 \\
4+6 & 5+5 & 6+4 \\
7+3 & 8+2 & 9+1
\end{pmatrix} = \begin{pmatrix}
10 & 10 & 10 \\
10 & 10 & 10 \\
10 & 10 & 10
\end{pmatrix}
$  

#### **B. Multiplication par un Scalaire**  
Si $ \lambda \in \mathbb{R} $, alors $ \lambda A $ est définie par :
$ (\lambda A)_{ij} = \lambda \cdot a_{ij} $  

**Exemple :**  

$
2A = 2 \begin{pmatrix}
1 & 2 & 3 \\
4 & 5 & 6 \\
7 & 8 & 9
\end{pmatrix} = \begin{pmatrix}
2 & 4 & 6 \\
8 & 10 & 12 \\
14 & 16 & 18
\end{pmatrix}
$  

#### **C. Produit Matriciel**  
Si $ A $ est de taille $ m \times n $ et $ B $ de taille $n \times p $, alors $ C = A \times B $ est de taille $ m \times p $ avec : $\qquad$
$ c_{ij} = \sum_{k=1}^n a_{ik} \cdot b_{kj} $  

- **Le produit matriciel $A \times B$ est possible uniquement si le nombre de colonnes dans $𝐴$ est égal au nombre de lignes dans $𝐵$**
- **Le produit matriciel n'est pas commutatif ($A \times B$ n'est pas forcement égal à $B \times A$).**

**Exemple :**  

$
A = \begin{pmatrix}
1 & 2 & 3 \\
4 & 5 & 6 \\
7 & 8 & 9
\end{pmatrix}, \quad
B = \begin{pmatrix}
9 & 8 \\
6 & 5 \\
3 & 2
\end{pmatrix}
$

$
A \times B = \begin{pmatrix}
(1 \cdot 9 + 2 \cdot 6 + 3 \cdot 3) & (1 \cdot 8 + 2 \cdot 5 + 3 \cdot 2) \\
(4 \cdot 9 + 5 \cdot 6 + 6 \cdot 3) & (4 \cdot 8 + 5 \cdot 5 + 6 \cdot 2) \\
(7 \cdot 9 + 8 \cdot 6 + 9 \cdot 3) & (7 \cdot 8 + 8 \cdot 5 + 9 \cdot 2)
\end{pmatrix} = \begin{pmatrix}
30 & 24 \\
84 & 69 \\
138 & 114
\end{pmatrix}
$  

#### **D. Transposée d’une Matrice**  
La transposée $ A^T $ est obtenue en échangeant les lignes et les colonnes.  

**Exemple :**  

$
A = \begin{pmatrix}
1 & 2 & 3 \\
4 & 5 & 6
\end{pmatrix}, \quad
A^T = \begin{pmatrix}
1 & 4 \\
2 & 5 \\
3 & 6
\end{pmatrix}
$  



### **Exercices d’Application**  

#### **Exercice 1 (Addition & Multiplication par un Scalaire)**  
Soient : 

$
A = \begin{pmatrix}
2 & 0 & -1 \\
3 & 1 & 4 \\
-2 & 5 & 7
\end{pmatrix}, \quad
B = \begin{pmatrix}
1 & 3 & 2 \\
-4 & 0 & 5 \\
6 & -2 & 1
\end{pmatrix} et \quad
C = \begin{pmatrix}
1 & 1 & 1 \\
3 & 0 & 2
\end{pmatrix}
$  

Calculer si possible:  
1. $ A + B $
2. $ B + C $
3. $ 3A - 2B $  

#### **Exercice 2 (Produit Matriciel)**  
Soient :  
$
A = \begin{pmatrix}
-1 & 3 \\
2 & 4
\end{pmatrix}, \quad
B = \begin{pmatrix}
0 & -1 \\
4 & 2
\end{pmatrix}, \quad
C = \begin{pmatrix}
1 & 2 & 3 \\
2 & 9 & 6 \\
\end{pmatrix}
$ $\quad$
$
D = \begin{pmatrix}
4 \\
0 \\
7 \\
\end{pmatrix}
$ $\quad$
$
E = \begin{pmatrix}
3 & 2 & 3 \\
\end{pmatrix}
$

1. Calculer $ A \times B $ et $ B \times A $ puis conclut.
2. Calculer si possible :  
   2.1. $ C \times E $  
   2.2. $ D \times E $  
   2.3. $ E \times D $  

#### **Exercice 3 (Application Linéaire)**  
Soit $ f: \mathbb{R}^3 \rightarrow \mathbb{R}^3 $ définie par :  
$
f(x, y, z) = (2x - y + z, x + 3y - 2z, -x + 4y + 5z)
$  
1. Donner la matrice associée $ A $.  
2. Calculer $ f(1, -1, 2) $ en utilisant $ A $.  


In [53]:
import numpy as np
# Définition des matrices
A = np.array([[2, 0, -1], [3, 1, 4], [-2, 5, 7]])
B = np.array([[1, 3, 2], [-4, 0, 5], [6, -2, 1]])
C = np.array([[1, 1, 1], [3, 0, 2]])  # Note: C a une forme (2,3), incompatible avec A et B (3,3)
# 1. A + B
print(" A + B = \n", A + B)
# 2. B + C
#print("\n B + C =\n", B + C)
# 3. 3A - 2B
print("\n 3A - 2B =\n", 3*A - 2*B)

 A + B = 
 [[ 3  3  1]
 [-1  1  9]
 [ 4  3  8]]

 3A - 2B =
 [[  4  -6  -7]
 [ 17   3   2]
 [-18  19  19]]


In [61]:
# Définition des matrices
A = np.array([[-1, 3], [2, 4]])
B = np.array([[0, -1], [4, 2]])
C = np.array([[1, 2, 3], [2, 9, 6]])
D = np.array([[4], [0], [7]])  # (3x1)
E = np.array([[3, 2, 3]])      # (1x3)

# 1. A × B et B × A
print(" A × B =\n", np.dot(A, B))
print("\n B × A =\n", np.dot(B, A))
print("Conclusion : ---- ---- ----")
# 2.1 C × E
#print("\n C × E =\n", C @ E)
# 2.2 D × E 
print("\n D × E =\n", D @ E)
# 2.3 E × D 
print("\n E × D =\n", E @ D)

 A × B =
 [[12  7]
 [16  6]]

 B × A =
 [[-2 -4]
 [ 0 20]]
Conclusion : ---- ---- ----

 D × E =
 [[12  8 12]
 [ 0  0  0]
 [21 14 21]]

 E × D =
 [[33]]


In [65]:
# 1. Matrice associée A
A = np.array([[2, -1, 1], [1, 3, -2], [-1, 4, 5]])
print("1. Matrice A =\n", A)
# 2. Calcul de f(1, -1, 2)
vecteur = np.array([1, -1, 2])
print("\n2. f(1, -1, 2) =", np.dot(A, vecteur))

1. Matrice A =
 [[ 2 -1  1]
 [ 1  3 -2]
 [-1  4  5]]

2. f(1, -1, 2) = [ 5 -6  5]


In [95]:
a = np.array([1,2,3]) 
b = np.array([4,5,6])
np.dot(a,b)

32

----
### **1.2.3. Calcul de l’Inverse d’une Matrice**   
----  
#### **A. Introduction : Pourquoi Calculer l’Inverse d’une Matrice ?**  

L’inverse d’une matrice est un concept fondamental en algèbre linéaire, particulièrement utile en **intelligence artificielle** pour :  
- **Résoudre des systèmes d’équations linéaires** (alternative à la méthode du pivot de Gauss).  
- **Trouver des solutions optimales** dans les problèmes d’optimisation (régression linéaire, moindres carrés).  
- **Effectuer des transformations géométriques inverses** (en vision par ordinateur, robotique).

**Définition :**  
Une matrice carrée $A$ d’ordre $n$ est **inversible** s’il existe une matrice $B$ telle que :  
$
A \times B = B \times A = I_n
$  
où $ I_n $ est la matrice identité. On note $ B = A^{-1} $.  

#### **B. Conditions d’Inversibilité**  
Une matrice $ A $ est inversible **si et seulement si** :  
- Son **déterminant est non nul** ($ \det(A) \neq 0 $).  
- Ses colonnes (ou lignes) sont **linéairement indépendantes**.  

#### **C. Méthodes pour Calculer l’Inverse d’une Matrice**  

##### **i) Méthode du Déterminant et des Comatrice**  
Formule de l’inverse d’une matrice $ A $ :  
$$ A^{-1} = \frac{1}{\det(A)} \cdot \text{Com}(A)^T $$  où :
- $ \det(A) $ est le **déterminant** de la matrice,
- $ \text{Com}(A) $ est la **comatrice** de $ A $ (la matrice des cofacteurs),
- $ \text{Com}(A)^T $ est la **transposée** de la comatrice.

##### **ii) Méthode par Pivot de Gauss (Élimination Linéaire)**  
On transforme $ [A | I_n] $ en $ [I_n | A^{-1}] $ via des opérations élémentaires.  

**Exemple :**  
$$
\begin{pmatrix}
1 & 2 & 3 & | & 1 & 0 & 0 \\
0 & 1 & 4 & | & 0 & 1 & 0 \\
5 & 6 & 0 & | & 0 & 0 & 1
\end{pmatrix} \xrightarrow{\text{opérations}} \begin{pmatrix}
1 & 0 & 0 & | & -24 & 18 & 5 \\
0 & 1 & 0 & | & 20 & -15 & -4 \\
0 & 0 & 1 & | & -5 & 4 & 1
\end{pmatrix}
$$ 

#### **D. Applications de l’Inverse Matriciel**  

##### **i) Résolution de Systèmes Linéaires**  
Si $ AX = B $, alors $ X = A^$
\begin{cases}
x + 2y + 3z = 6 \\
y + 4z = 9 \\
5x + 6y = 3
\end{cases} \Rightarrow X = A^{-1} \begin{pmatrix} 6 \\ 9 \\ 3 \end{pmatrix} = \begin{pmatrix} -24 \cdot 6 + 18 \cdot 9 + 5 \cdot 3 \\ 20 \cdot 6 -15 \cdot 9 -4\cdot 3 \\ -5 \cdot 6 +4 \cdot 9 +1\cdot 3 \end{pmatrix} = \begin{pmatrix} 33 \\ -27 \\ 9 \end{pmatrix}
$  trix} 1 \\ -3 \\ 3 \end{pmatrix}
$   


##### **ii) Régression Linéaire (Moindres Carrés)**  
La solution de $ \theta = (X^T X)^{-1} X^T Y $ nécessite l’inversion de $ X^T X $.  
Mais attention, on préfère des méthodes numériques approximatives comme la **descente de gradient** car l'inversion de grande matrice coûte très cher.


er.


In [109]:
import numpy as np
# Définition de la matrice A et du vecteur B
A = np.array([[1, 2, 3],
              [0, 1, 4],
              [5, 6, 0]])
B = np.array([6, 9, 3])

# Vérification que A est inversible
if np.linalg.det(A) != 0:
    # Calcul de l'inverse de A
    A_inv = np.linalg.inv(A)
    # Solution X = A^{-1} * B
    X = np.dot(A_inv, B)
    print("Solution X =", X)
else:
    print("La matrice A n'est pas inversible.")

Solution X = [ 33. -27.   9.]




---


---

## **Exercices d’Application**  

### **Exercice 1 (Inverse par Cofacteurs)**  
Calculer $ A^{-1} $ pour :  
$
A = \begin{pmatrix}
2 & 0 & -1 \\
3 & 1 & 4 \\
-2 & 5 & 7
\end{pmatrix}
$  

### **Exercice 2 (Résolution de Système)**  
Résoudre en utilisant $ A^{-1} $ :  
$
\begin{cases}
2x - z = 1 \\
3x + y + 4z = 0 \\
-2x + 5y + 7z = 3
\end{cases}
$  

### **Exercice 3 (Inverse par Gauss)**  
Trouver $ B^{-1} $ par pivot de Gauss :  
$
B = \begin{pmatrix}
1 & 0 & 2 \\
-1 & 3 & 1 \\
2 & 4 & 0
\end{pmatrix}
$  

---

## **Corrigés (Extraits)**  

### **Corrigé Exercice 1**  
$
\det(A) = 2(1 \cdot 7 - 4 \cdot 5) - 0 + (-1)(3 \cdot 5 - 1 \cdot (-2)) = -46  
$  
$
A^{-1} = -\frac{1}{46} \begin{pmatrix}
-13 & 5 & 1 \\
29 & 12 & -11 \\
17 & -10 & 2
\end{pmatrix}
$  

### **Corrigé Exercice 2**  
$
X = A^{-1} \begin{pmatrix} 1 \\ 0 \\ 3 \end{pmatrix} = \begin{pmatrix} 1 \\ -2 \\ 1 \end{pmatrix}
$  

### **Corrigé Exercice 3**  
$
B^{-1} = \begin{pmatrix}
-4 & 8 & -6 \\
2 & -4 & 3 \\
10 & -4 & 3
\end{pmatrix}
$  

---

**Conclusion :** L’inversion matricielle est cruciale en IA pour la résolution de problèmes linéaires et l’optimisation. Les méthodes présentées (déterminant, cofacteurs, Gauss) sont des outils de base en algèbre linéaire appliquée.

# Travail à rendre avant Jeudi 1er mai à 23h 59.  


1. Implémente une fonction **produit_scalaire(vecteur1, vecteur2)** qui prend en entrée deux listes et qui retourne le produit scalaire des deux vecteurs s'ils ont même taille sinon il retourne **None**
2. Implémente une fonction **norme_1(vecteur)** ( resp. **norme_2(vecteur)** ) qui prend en entrée une liste ou un tuple de nombres réels puis retourne la **norme 1** (resp. la **norme 2**) du vecteur en utilisant **numpy**